"""Configuration module for Magic Hour LangGraph Workflow."""
from .settings import (
    FAL_KEY,
    PRODIA_KEY,
    IMAGE_MODELS,
    VIDEO_MODELS,
    EDIT_MODEL,
    DEFAULT_IMAGE_WIDTH,
    DEFAULT_IMAGE_HEIGHT,
    DEFAULT_NUM_IMAGES,
    DEFAULT_VIDEO_DURATION,
    DEFAULT_FAL_MODEL_NAME,
    DEFAULT_TEMPERATURE,
    DEFAULT_MAX_TOKENS,
)

__all__ = [
    "FAL_KEY",
    "PRODIA_KEY",
    "IMAGE_MODELS",
    "VIDEO_MODELS",
    "EDIT_MODEL",
    "DEFAULT_IMAGE_WIDTH",
    "DEFAULT_IMAGE_HEIGHT",
    "DEFAULT_NUM_IMAGES",
    "DEFAULT_VIDEO_DURATION",
    "DEFAULT_FAL_MODEL_NAME",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_MAX_TOKENS",
]
