"""Video generation tool using fal.ai API."""
import os
import json
import time
import tempfile
from typing import Literal

import fal_client
import requests
from pydantic import BaseModel, Field
from langchain_core.tools import tool

# Configure fal.ai
fal_client.api_key = os.getenv("FAL_KEY")

# Use same model as smolagents for consistency
VIDEO_MODEL = "fal-ai/bytedance/seedance/v1/pro/fast/text-to-video"


class VideoGenerationInput(BaseModel):
    """Input schema for video generation."""
    prompt: str = Field(
        description="Detailed text description of the video to generate. Describe the scene, action, and style."
    )
    mode: Literal["fast", "pro"] = Field(
        default="pro",
        description="Generation mode: 'fast' for quicker results, 'pro' for higher quality"
    )
    duration: int = Field(
        default=5,
        description="Video duration in seconds (4-8 seconds)"
    )


@tool(args_schema=VideoGenerationInput)
def generate_video(
    prompt: str,
    mode: Literal["fast", "pro"] = "pro",
    duration: int = 5
) -> str:
    """Generate a video from a text prompt using AI models.

    Use this tool when the user wants to create a video from a text description.
    Returns the file path to the generated video.

    Args:
        prompt: Detailed text description of the video to generate
        mode: 'fast' for quicker generation, 'pro' for higher quality
        duration: Video duration in seconds (4-8)

    Returns:
        String containing the file path of the generated video
    """
    # Fixed duration at 6 seconds (matching smolagents)
    duration = 6

    # Debug logging
    debug_info = {
        "prompt": prompt[:100] + "..." if len(prompt) > 100 else prompt,
        "mode": mode,
        "model_id": VIDEO_MODEL,
        "duration": duration,
        "resolution": "720p",
    }
    print(f"\n{'='*80}")
    print(f"DEBUG - Video Generation Tool Called:")
    print(json.dumps(debug_info, indent=2))
    print(f"{'='*80}\n")

    args = {
        "prompt": prompt,
        "duration": duration,
        "resolution": "720p",
    }

    try:
        st = time.time()
        print(f"DEBUG - Calling fal_client.submit({VIDEO_MODEL})...")
        result = fal_client.submit(VIDEO_MODEL, arguments=args).get()
        et = time.time()

        print(f"DEBUG - fal.ai response received in {et - st:.2f}s")
        print(f"DEBUG - Result keys: {result.keys() if result else 'None'}")

        if not result or "video" not in result:
            print(f"DEBUG - ERROR: No video in result. Full result: {result}")
            return "Error: No video generated by fal.ai"

        video_url = result["video"]["url"]
        print(f"DEBUG - Video URL: {video_url}")

        # Download the video
        print(f"DEBUG - Downloading video...")
        response = requests.get(video_url, timeout=300)  # Longer timeout for videos
        response.raise_for_status()

        temp_file = tempfile.NamedTemporaryFile(suffix=".mp4", delete=False)
        temp_file.write(response.content)
        temp_file.close()

        print(f"DEBUG - Video saved to: {temp_file.name}")
        result_msg = f"Successfully generated video:\n- {temp_file.name}"
        print(f"DEBUG - Video generation result:\n{result_msg}")
        return result_msg

    except Exception as e:
        print(f"DEBUG - Video generation EXCEPTION: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return f"Failed to generate video: {str(e)}"
